FROM microsoft/dotnet:2.2-aspnetcore-runtime AS base
FROM microsoft/dotnet:2.2-sdk AS build

WORKDIR /src

# restore
COPY ["./API/Agilistas.csproj", "API/"]
RUN dotnet restore API/Agilistas.csproj
COPY ModelTests/ModelTests.csproj ./ModelTests/
RUN dotnet restore ModelTests/ModelTests.csproj

# copy src
COPY . .

# test
RUN dotnet test ModelTests/ModelTests.csproj