FROM microsoft/dotnet:2.2-aspnetcore-runtime AS base
FROM microsoft/dotnet:2.2-sdk AS build

WORKDIR /src

# restore
COPY ["./API/Agilistas.csproj", "API/"]
RUN dotnet restore API/Agilistas.csproj
COPY ./ModelTests/ModelTests.csproj ./ModelTests/
RUN dotnet restore ModelTests/ModelTests.csproj

# copy src
COPY . .
RUN chmod +x ModelTests/wait-for-it.sh
RUN chmod +x ModelTests/entrypoint-tests.sh
#RUN /bin/bash ModelTests/entrypoint-tests.sh <--have alternated between this an the RUN on line 19. Either way, these happen before db is available even if I put in long pauses

# test
RUN dotnet test ModelTests/ModelTests.csproj
