
WORKDIR /src

# install SQL Server drivers and tools
RUN apt-get update && ACCEPT_EULA=Y apt-get install -y msodbcsql mssql-tools
RUN echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
RUN /bin/bash -c "source ~/.bashrc"

# restore

COPY DbTests/DbTests.csproj ./DbTests/
RUN dotnet restore DbTests/DbTests.csproj

# copy src
COPY . .

# test
RUN dotnet test DbTests/DbTests.csproj